### ISSUE TITLE
OSError: dlopen(...6): image not found)

### ISSUE THREAD

**Issue by motiwari** [facebookresearch/slbo#2]
I can't get the code to run; I've installed `mujoco` and verified the install works, as well as installed all the dependencies, but when I try to run the command in the `README` I get the following error:

```
(p36-default)➜  slbo git:(master) ✗ python main.py -c configs/algos/slbo.yml configs/envs/half_cheetah.yml -s log_dir=/tmp

2019-02-07 12:05:54,997947 - lunzi/nn/patch.py:31 - Monkey patching TensorFlow...
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from slbo.partial_envs import make_env
  File "/Users/motiwari/Desktop/aaTengyuWork/slbo/slbo/partial_envs.py", line 3, in <module>
    from slbo.envs.mujoco.half_cheetah_env import HalfCheetahEnv
  File "/Users/motiwari/Desktop/aaTengyuWork/slbo/slbo/envs/mujoco/half_cheetah_env.py", line 3, in <module>
    from rllab.envs.mujoco import half_cheetah_env
  File "/Users/motiwari/p36-default/lib/python3.6/site-packages/rllab-0.1.0-py3.6.egg/rllab/envs/mujoco/half_cheetah_env.py", line 5, in <module>
    from rllab.envs.mujoco.mujoco_env import MujocoEnv
  File "/Users/motiwari/p36-default/lib/python3.6/site-packages/rllab-0.1.0-py3.6.egg/rllab/envs/mujoco/mujoco_env.py", line 8, in <module>
    from rllab.mujoco_py import MjModel, MjViewer
  File "/Users/motiwari/p36-default/lib/python3.6/site-packages/rllab-0.1.0-py3.6.egg/rllab/mujoco_py/__init__.py", line 1, in <module>
    from .mjviewer import MjViewer
  File "/Users/motiwari/p36-default/lib/python3.6/site-packages/rllab-0.1.0-py3.6.egg/rllab/mujoco_py/mjviewer.py", line 7, in <module>
    from . import mjcore, mjconstants, glfw
  File "/Users/motiwari/p36-default/lib/python3.6/site-packages/rllab-0.1.0-py3.6.egg/rllab/mujoco_py/mjcore.py", line 6, in <module>
    from .mjlib import mjlib
  File "/Users/motiwari/p36-default/lib/python3.6/site-packages/rllab-0.1.0-py3.6.egg/rllab/mujoco_py/mjlib.py", line 17, in <module>
    mjlib = cdll.LoadLibrary(libfile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/motiwari/p36-default/lib/python3.6/site-packages/rllab-0.1.0-py3.6.egg/vendor/mujoco/libmujoco131.dylib, 6): image not found
```

FWIW, I upgraded to Mojave recently which has broken a lot of things (had to upgrade GCC, etc. to even get to this error). 

I also tried changing all instances of  `rllab.envs.mujoco` to just `mujoco` but then get errors that `MjViewer, MjModel` are not found.

Also, when I run the command `python main.py -c configs/algos/slbo.yml configs/envs/half_cheetah.yml -s log_dir=/tmp`, I get a popup from OSX asking if I want to allow the program to access the network. The program errors and dies before I can respond.

**Comment by motiwari** [comment]
For posterity: I figured this out. You need to install `baselines-4.x.x` from `https://github.com/openai/baselines`, and can't just do `pip install baselines` which installs `baselines-0.1.5`.
