### ISSUE TITLE
lunzi patch fails

### ISSUE THREAD

**Issue by amir-abdi** [facebookresearch/slbo#4]
Tensorflow version == 1.14.0
Monkey patching in `lunzi/nn/patch.py` fails with the following error:
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import lunzi.nn as nn
  File "/slbo/lunzi/__init__.py", line 3, in <module>
    import lunzi.nn
  File "//slbo/lunzi/nn/__init__.py", line 2, in <module>
    from . import patch
  File "//slbo/lunzi/nn/patch.py", line 61, in <module>
    monkey_patch()
  File "//slbo/lunzi/nn/patch.py", line 56, in monkey_patch
    value = tf.__dict__[method]
KeyError: 'abs'
```

Checked the `tf.__dict__` and here are its contents:

`
{'_dw_wrapped_module': <module 'tensorflow' from '/home/amirabdi/miniconda3/envs/artisynth-rl/lib/python3.6/site-packages/tensorflow/__init__.py'>, '_dw_module_name': '', '_dw_deprecated_printed': set(), '_dw_warning_count': 0, '__name__': 'tensorflow', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None}
`

Which does not contain `abs` as well and the majority of the other patched methods in the `monkey_patch` function.

**Comment by roosephu** [comment]
Could you please try a lower version of TF, e.g., 1.13.2? TensorFlow is migrating to eager execution and is modulizing functions, so many functions are not available through `tf.*`.

**Comment by amir-abdi** [comment]
Thank you for the suggestion.
You are right. TF version 1.13.2 is the last one with the mentioned methods.

Check the #5 Pull Request.
